from enum import Enum


class RuleTriggerKeyword(str, Enum):
    AMOUNT_EXACTLY = "amount_exactly"
    AMOUNT_LESS = "amount_less"
    AMOUNT_MORE = "amount_more"
    ANY_NOTES = "any_notes"
    BUDGET_IS = "budget_is"
    CATEGORY_IS = "category_is"
    CURRENCY_IS = "currency_is"
    DESCRIPTION_CONTAINS = "description_contains"
    DESCRIPTION_ENDS = "description_ends"
    DESCRIPTION_IS = "description_is"
    DESCRIPTION_STARTS = "description_starts"
    DESTINATION_ACCOUNT_IS = "destination_account_is"
    FROM_ACCOUNT_CONTAINS = "from_account_contains"
    FROM_ACCOUNT_ENDS = "from_account_ends"
    FROM_ACCOUNT_IS = "from_account_is"
    FROM_ACCOUNT_STARTS = "from_account_starts"
    HAS_ANY_BUDGET = "has_any_budget"
    HAS_ANY_CATEGORY = "has_any_category"
    HAS_ANY_TAG = "has_any_tag"
    HAS_ATTACHMENTS = "has_attachments"
    HAS_NO_BUDGET = "has_no_budget"
    HAS_NO_CATEGORY = "has_no_category"
    HAS_NO_TAG = "has_no_tag"
    NOTES_ARE = "notes_are"
    NOTES_CONTAINS = "notes_contains"
    NOTES_CONTAIN = "notes_contain"
    NOTES_END = "notes_end"
    NOTES_START = "notes_start"
    NOTES_STARTS = "notes_starts"
    NO_NOTES = "no_notes"
    SOURCE_ACCOUNT_IS = "source_account_is"
    SOURCE_ACCOUNT_STARTS = "source_account_starts"
    TAG_IS = "tag_is"
    TO_ACCOUNT_CONTAINS = "to_account_contains"
    TO_ACCOUNT_ENDS = "to_account_ends"
    TO_ACCOUNT_IS = "to_account_is"
    TO_ACCOUNT_STARTS = "to_account_starts"
    TRANSACTION_TYPE = "transaction_type"

    def __str__(self) -> str:
        return str(self.value)
